api_platform:
  defaults:
    pagination_enabled: false
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]
  swagger:
    api_keys:
      access_token:
        name: Authorization
        type: header