api_platform:
  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]
  swagger:
    api_keys:
      access_token:
        name: Authorization
        type: header