version: '3'

services:
  # Development Database
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - mynetwork
    ports:
      - "5432:5432" # Expose the port

  # Test Database
  database_test:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app_test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_test_data:/var/lib/postgresql/data:rw
    networks:
      - mynetwork
    ports:
      - "5433:5432" # Expose a different port for the test database

volumes:
  database_data:
  database_test_data:

networks:
  mynetwork:
    external: false
